### ISSUE TITLE
android.view.InflateException, when using alerter 2.0.4

### ISSUE THREAD

**Issue by moda20** [Tapadoo/Alerter#145]
hey I jus tried your library alerter with the version 2.0.4 and got into this issue : 
```
Uncaught exception from plugin
                 android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class <unknown>
                 Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class <unknown>
                 Caused by: java.lang.reflect.InvocationTargetException
                     at java.lang.reflect.Constructor.newInstance0(Native Method)
                     at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                     at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                     at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
```
I couldn't find anyway of fixing it. 
I must note that I was using the 3.0.0 version which had problems with not finding some classes.

**Comment by moda20** [comment]
I fixed this issue by changing in the `alerter_alert_view.xml` the attribute `android:foreground`
from `?attr/selectableItemBackground`
to `?android:attr/selectableItemBackground`

Can you fix it in your repository because that is just a workaround ?
