### ISSUE TITLE
ClassCastException: android.support.constraint.ConstraintLayout$LayoutParams cannot be cast to android.widget.LinearLayout$LayoutParams

### ISSUE THREAD

**Issue by lll-01** [Tapadoo/Alerter#168]
.ClassCastException: android.support.constraint.ConstraintLayout$LayoutParams cannot be cast to android.widget.LinearLayout$LayoutParams
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3390)
        at android.app.ActivityThread.-wrap17(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1812)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6758)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
     Caused by: java.lang.ClassCastException: android.support.constraint.ConstraintLayout$LayoutParams cannot be cast to android.widget.LinearLayout$LayoutParams
        at com.tapadoo.alerter.Alert.setContentGravity(Alert.kt:69)
        at com.tapadoo.alerter.Alerter.setContentGravity(Alerter.kt:121)

**Comment by kpmmmurphy** [comment]
Hi @lll-01, I've added a check to prevent this casting exception in version 4.0.1
