### ISSUE TITLE
Alerter failes to load

### ISSUE THREAD

**Issue by venkyvc** [Tapadoo/Alerter#215]
hey there..!!

I implemented the alerter library into my project with version as 5.1.1 but when application runs it fails to load the alerter and force closes the app. wants to know how can i enable it properly. 
I'm using androidx  in my project

**Comment by rezaiyan** [comment]
> hey there..!!
> 
> I implemented the alerter library into my project with version as 5.1.1 but when application runs it fails to load the alerter and force closes the app. wants to know how can i enable it properly.
> I'm using androidx in my project

Could you explain more and share some evidence

**Comment by venkyvc** [comment]
I Implemented the alerter library into my project with the version number as 5.1.1 and when the application runs and executes the method of showing alerter. Application crashes and throws error as below.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.coderedinnovations.allioservices, PID: 14409
    java.lang.NoClassDefFoundError: Failed resolution of: [Lkotlin/reflect/KProperty;
        at com.tapadoo.alerter.Alert.<clinit>(Unknown Source:1)
        at com.tapadoo.alerter.Alerter$Companion.create(Alerter.kt:618)
        at com.tapadoo.alerter.Alerter$Companion.create(Alerter.kt:598)
        at com.tapadoo.alerter.Alerter.create(Unknown Source:2)
        at com.coderedinnovations.allioservices.UserFragments.PhoneLoginActivity$5.onVerificationFailed(PhoneLoginActivity.java:151)
        at com.google.firebase.auth.api.internal.zzex.zza(com.google.firebase:firebase-auth@@19.2.0:4)
        at com.google.firebase.auth.api.internal.zzfa.run(com.google.firebase:firebase-auth@@19.2.0:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7211)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:903)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.reflect.KProperty" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.coderedinnovations.allioservices-wmtTHFZGG7gaHH4IMnbF9A==/base.apk"],nativeLibraryDirectories=[/data/app/com.coderedinnovations.allioservices-wmtTHFZGG7gaHH4IMnbF9A==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tapadoo.alerter.Alert.<clinit>(Unknown Source:1) 
        at com.tapadoo.alerter.Alerter$Companion.create(Alerter.kt:618) 
        at com.tapadoo.alerter.Alerter$Companion.create(Alerter.kt:598) 
        at com.tapadoo.alerter.Alerter.create(Unknown Source:2) 
        at com.coderedinnovations.allioservices.UserFragments.PhoneLoginActivity$5.onVerificationFailed(PhoneLoginActivity.java:151) 
        at com.google.firebase.auth.api.internal.zzex.zza(com.google.firebase:firebase-auth@@19.2.0:4) 
        at com.google.firebase.auth.api.internal.zzfa.run(com.google.firebase:firebase-auth@@19.2.0:4) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:227) 
        at android.app.ActivityThread.main(ActivityThread.java:7211) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:903)

**Comment by kpmmmurphy** [comment]
Hey @venkyvc, are you using Kotlin in your project? Please try reverting to version 2.0.6 of the library.

**Comment by venkyvc** [comment]
Yah that's what I did thanks for the library by the way it saved my day.
