### ISSUE TITLE
[BUG] Error in InitView

### ISSUE THREAD

**Issue by PaolinoAngeletti** [Tapadoo/Alerter#236]
we have revelead this error. 
A try catch would solve the problem.

"
Caused by android.content.res.Resources$NotFoundException
Unable to find resource ID #0x7f08006a
"
Stack:
Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f08006a
       at android.content.res.Resources.getResourceName(Resources.java:2070)
       at android.content.res.Resources.loadDrawableForCookie(Resources.java:2441)
       at android.content.res.Resources.loadDrawable(Resources.java:2381)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
       at android.widget.ImageView.<init>(ImageView.java:146)
       at android.widget.ImageView.<init>(ImageView.java:135)
       at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
       at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at android.view.View.inflate(View.java:18532)
       at com.tapadoo.alerter.Alert.initView(Alert.java:122)
       at com.tapadoo.alerter.Alert.<init>(Alert.java:93)
       at com.tapadoo.alerter.Alerter.create(Alerter.java:61)
       at external.DialogMessage.showMessage(DialogMessage.java:142)
       at mbe.mp.login.LoginCognito$10.run(LoginCognito.java:566)
       at thread.ThreadUtils.runOnUiThread(ThreadUtils.java:25)
       at mbe.mp.login.LoginCognito.mostraMessaggioUtente(LoginCognito.java:561)
       at mbe.mp.login.LoginCognito.verificaInserimentoMail(LoginCognito.java:350)
       at mbe.mp.login.LoginCognito.verificaInserimentoDati(LoginCognito.java:338)
       at mbe.mp.login.LoginCognito.access$800(LoginCognito.java:54)
       at mbe.mp.login.LoginCognito$4.onClick(LoginCognito.java:280)
       at android.view.View.performClick(View.java:4780)
       at android.view.ViewDebug$3.run(ViewDebug.java:826)
       at android.os.Handler.handleCallback(Handler.java:756)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5314)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:374)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by kpmmmurphy** [comment]
Hey @PaolinoAngeletti, could you please provide the library version, and code examples of where this exception is thrown? Many thanks.

**Comment by ferostar** [comment]
I see it myself. Not all the time, but once in a while. Happens when the alerter is created:

`Alerter alert = Alerter.create(activity);` I'm using `com.tapadoo.android:alerter:4.0.2`.

**Comment by SoftwareAdvise** [comment]
So ? There is a solution ?
