### ISSUE TITLE
ResourceNotFound Exception

### ISSUE THREAD

**Issue by Szanik** [Tapadoo/Alerter#292]
Trying to call a simple Alert via 

`Alerter.create(activity)
                    .setTitle("Hey").show()`
                    
                   
Gives me the following exception:

` FATAL EXCEPTION: main
                                                                                                    Process: de.szanik.walkingtreats, PID: 17546
                                                                                                    android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                                                                    	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:259)
                                                                                                    	at android.content.res.Resources.getDrawableForDensity(Resources.java:1049)
                                                                                                    	at android.content.res.Resources.getDrawable(Resources.java:989)
                                                                                                    	at android.content.Context.getDrawable(Context.java:952)
                                                                                                    	at androidx.core.content.ContextCompat$Api21Impl.getDrawable(ContextCompat.java:1110)
                                                                                                    	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:526)
                                                                                                    	at com.tapadoo.alerter.utils.ExAlertKt.getRippleDrawable(ExAlert.kt:24)
                                                                                                    	at com.tapadoo.alerter.Alert.onAttachedToWindow(Alert.kt:176)
                                                                                                    	at android.view.View.dispatchAttachedToWindow(View.java:23198)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3694)
                                                                                                    	at android.view.ViewGroup.addViewInner(ViewGroup.java:5548)
                                                                                                    	at android.view.ViewGroup.addView(ViewGroup.java:5324)
                                                                                                    	at android.view.ViewGroup.addView(ViewGroup.java:5264)
                                                                                                    	at android.view.ViewGroup.addView(ViewGroup.java:5236)
                                                                                                    	at com.tapadoo.alerter.Alerter$show$$inlined$let$lambda$1.run(Alerter.kt:47)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8893)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)`
                                                                                                    	
                                                     
Android 14
One UI 6.0
LibVersion 7.2.4
using it in an app written in jet compose

**Comment by superdiazzz** [comment]
got the same problem, do you get solution?

**Comment by Szanik** [comment]
i used this:

https://github.com/akardas16/Alerter
