### ISSUE TITLE
Crashes - NullPointerException

### ISSUE THREAD

**Issue by MrVipinVijayan** [Tapadoo/Alerter#56]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference
                                                                                  at com.tapadoo.alerter.Alerter$1.run(Alerter.java:90)
                                                                                  at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1140)
                                                                                  at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
                                                                                  at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
                                                                                  at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:696)
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:628)
                                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
                                                                                  at android.os.Handler.handleCallback(Handler.java:815)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                  at android.os.Looper.loop(Looper.java:207)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5740)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)

**Comment by Sabirjan** [comment]
This problem has also happened in my application.Is there a solution?Occurs when more notifications are displayed.

**Comment by iceberg1369** [comment]
yes, this error occurs when multiple notifications are opened at once

**Comment by qbait** [comment]
I replaced my Snackbar alerts with Alerter and I'm getting also this NPE, what's the best way to deal with it?

**Comment by kpmmmurphy** [comment]
In version 2.0.0 I've added a try-catch to handle any unexpected errors here.
