### ISSUE TITLE
Binary XML file line #29

### ISSUE THREAD

**Issue by WangJian0** [Tapadoo/Alerter#57]
I use this on Android Studio,and exception happened:
android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class android.support.v7.widget.AppCompatImageView
	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at android.view.View.inflate(View.java:19784)
	at com.tapadoo.alerter.Alert.initView(Alert.java:108)
	at com.tapadoo.alerter.Alert.<init>(Alert.java:79)
	at com.tapadoo.alerter.Alerter.create(Alerter.java:56)
	at com.coldstorage3.AlarmNotificationPackage.AlarmNotification.rnCallNative(AlarmNotification.java:64)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:148)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.view.InflateException: Binary XML file line #29: Error inflating class android.support.v7.widget.AppCompatImageView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)

can you give me some propose?
Thanks.

**Comment by guicunha** [comment]
Same error for, me what the resolution for it?
