### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Sabirjan** [Tapadoo/Alerter#71]
`   java.lang.NullPointerException
                                                                             at com.tapadoo.alerter.Alerter$1.run(Alerter.java:91)
                                                                             at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1050)
                                                                             at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1056)
                                                                             at android.animation.ValueAnimator.access$400(ValueAnimator.java:50)
                                                                             at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:644)
                                                                             at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:660)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:591)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:559)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
                                                                             at android.os.Handler.handleCallback(Handler.java:808)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                             at android.os.Looper.loop(Looper.java:229)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5493)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
                                                                             at dalvik.system.NativeStart.main(Native Method)`

**Comment by Sabirjan** [comment]
This problem has also happened in my application.Is there a solution?Occurs when more notifications are displayed.

**Comment by kpmmmurphy** [comment]
Hi @Sabirjan - I'm not sure why this crash is occurring, but I'll add some additional error handling to help guard against it.
