### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MrVipinVijayan** [Tapadoo/Alerter#77]
Hi,

The library is crashing.

Please provide a fix.

java.lang.NullPointerException: 
  at com.tapadoo.alerter.Alerter$1.run(Alerter.java:90)
  at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1119)
  at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
  at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
  at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
  at android.view.Choreographer.doCallbacks(Choreographer.java:672)
  at android.view.Choreographer.doFrame(Choreographer.java:605)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5441)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by kpmmmurphy** [comment]
Updated in version 2.0.1
