### ISSUE TITLE
Resource not found in icons

### ISSUE THREAD

**Issue by sijojosep** [Tapadoo/Alerter#81]
i had a problem when set icon to the alerter follow the 
creash report
==========

 NotFoundException for com.aitrich.android.orderpro
                                                                    android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/ic_map_marker_white_48dp.png from xml type xml resource ID #0x7f020102
                                                                        at android.content.res.Resources.loadXmlResourceParser(Resources.java:3059)
                                                                        at android.content.res.Resources.loadXmlResourceParser(Resources.java:3014)
                                                                        at android.content.res.Resources.getXml(Resources.java:1383)
                                                                        at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:586)
                                                                        at com.tapadoo.alerter.Alert.setIcon(Alert.java:471)
                                                                        at com.tapadoo.alerter.Alerter.setIcon(Alerter.java:342)
                                                                        at com.aitrich.android.orderpro.ui.fragment.operation.InventoryVoucherFormFragment$4.onClick(InventoryVoucherFormFragment.java:1732)
                                                                        at android.view.View.performClick(View.java:5269)
                                                                        at android.view.View$PerformClick.run(View.java:21556)
                                                                        at android.os.Handler.handleCallback(Handler.java:815)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                        at android.os.Looper.loop(Looper.java:207)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5776)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                                     Caused by: java.io.FileNotFoundException: Corrupt XML binary file
                                                                        at android.content.res.AssetManager.openXmlAssetNative(Native Method)
                                                                        at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:504)
                                                                        at android.content.res.Resources.loadXmlResourceParser(Resources.java:3041)
                                                                        at android.content.res.Resources.loadXmlResourceParser(Resources.java:3014) 
                                                                        at android.content.res.Resources.getXml(Resources.java:1383) 
                                                                        at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:586) 
                                                                        at com.tapadoo.alerter.Alert.setIcon(Alert.java:471) 
                                                                        at com.tapadoo.alerter.Alerter.setIcon(Alerter.java:342) 
                                                                        at com.aitrich.android.orderpro.ui.fragment.operation.InventoryVoucherFormFragment$4.onClick(InventoryVoucherFormFragment.java:1732) 
                                                                        at android.view.View.performClick(View.java:5269) 
                                                                        at android.view.View$PerformClick.run(View.java:21556) 
                                                                        at android.os.Handler.handleCallback(Handler.java:815) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                        at android.os.Looper.loop(Looper.java:207) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5776) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 

My code
=====

 Alerter.create(getActivity())
                                    .setText("Eelect destination location")
                                           .setBackgroundColorRes(R.color.colorAccent)
                                            .setIcon(R.drawable.ic_map_marker_white_48dp)
                                                .show();

**Comment by kpmmmurphy** [comment]
I've updated how drawables are loaded, this should be fixed in version 2.0.1
